### ISSUE TITLE
Update add card state to point out the error when one of the fields is not filled out

### ISSUE THREAD

**Issue by rwblickhan** [rwblickhan/Spreppy#42]
See `AddCardViewModel.handle(.saveTapped)`. We could maybe show some red text below the empty text field when this happens.

**Comment by aserputov** [comment]
Hey, I would like to work on this issue, could you please assign me ?

**Comment by rwblickhan** [comment]
Hey there, I won't be accepting external contributions until the design is a bit more firmed up (I wouldn't want you to waste your time building something that will just get replaced soon anyways!). In the meantime I encourage you to fork this repository if you want to play around a bit 🙂

**Comment by aserputov** [comment]
@rwblickhan Thank you 🙂
